create table if not exists public.discussion_views (
  id bigint generated by default as identity primary key,
  discussion_id uuid not null references public.discussions (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists discussion_views_discussion_id_idx
  on public.discussion_views (discussion_id);
create index if not exists discussion_views_created_at_idx
  on public.discussion_views (created_at desc);

alter table public.discussion_views enable row level security;

drop policy if exists "Anyone can read discussion views" on public.discussion_views;
create policy "Anyone can read discussion views"
on public.discussion_views
for select
using (true);

drop policy if exists "Anyone can create discussion views" on public.discussion_views;
create policy "Anyone can create discussion views"
on public.discussion_views
for insert
with check (true);
